### ISSUE TITLE
[SUGGESTION]  Roll the Bones logic 

### ISSUE THREAD

**Issue by tomovka** [WoWAnalyzer/WoWAnalyzer#4326] opened 2021-01-11 10:48 UTC
Outdated script seems to work okay for the basic needs, but the buff priority had changed according to the following logic:

(cumulative value) ≤ 2 - recast
(cumulative value) > 2 - wait out full duration 
                       
Broadside (BS)                    = 3 
True Bearing (TB)                = 3
Ruthless Precision (RP)       = 2 
Skull and Crossbones (SC)  = 2
Buried Treasure (BT)            = 1
Grand Melee (GM)              = 1  

However, if Sleight of Hand conduit is being used, the values change to:
 
BS = 2
TB = 2 
Rest stays the same
 
(This is because if using the conduit, we should always try to get 2+ buffs but not BT+GM)

**Comment by tyndivelspaz** [comment] 2021-03-05 17:05
This is a duplicate of #4239 We can use this information to help with that issue so we don't have double the work

**Closed as completed by tyndivelspaz** 2021-03-05 17:05 UTC
