### ISSUE TITLE
Undefined character + Error 404 on armory 

### ISSUE THREAD

**Issue by baronebirra82** [WoWAnalyzer/WoWAnalyzer#3500] opened 2020-02-24 23:03 UTC
If i try to go to my character's pages i get this error:
https://wowanalyzer.com/character/undefined/undefined/Gorak
which becomes a 404 error on WoW Armory:
https://worldofwarcraft.com/en-us/character/us/undefined/undefined/Gorak

how can i solve this? I have a regular account on warcraft logs, with the correct region and server
and this is my correct armory page: 
https://worldofwarcraft.com/en-us/character/eu/pozzo-delleternit%C3%A0/gorak

Can you help me?

**Comment by jnsebgosselin** [comment] 2020-07-07 23:21
I'm having the same problem and I'm also wondering why this is happening and how this could be fixed. It seems like a very common problem. For example, here is a log from my guild where 9 out of 20 characters are not correctly linked to their wow armory.

https://wowanalyzer.com/report/h2748w9RLdHaFMb3/11-Mythic+Maut+-+Kill+(6:01)

![image](https://user-images.githubusercontent.com/10170372/86854693-e6e2df00-c086-11ea-85ac-a76c41aa3422.png)

**Comment by Pewtro** [comment] 2020-07-08 05:46
Blizzard changed their API and we haven't updated to it yet.

**Comment by jnsebgosselin** [comment] 2020-07-12 20:42
@Pewtro I think this was fixed recently? I cannot reproduce the issue anymore.

**Comment by Pewtro** [comment] 2020-07-14 05:35
This specific issue is now fixed, as https://wowanalyzer.com/character/EU/Pozzo+dell'Eternit%C3%A0/Gorak/ is now searchable through the UI.

**Closed by Pewtro** 2020-07-14 05:35 UTC
