### ISSUE TITLE
[General] Pre Potions are not always correctly accounted for

### ISSUE THREAD

**Issue by CollCrom** [WoWAnalyzer/WoWAnalyzer#1218] opened 2018-01-19 22:03 UTC
In this log kidsmoke used a pre pot as shown in his buffs but the wow analyzer thinks that he did not use one.
https://wowanalyzer.com/report/9qhta2r4T3nFpvPx/20-Heroic+Varimathras+-+Kill+(3:04)/Kidsmoke
https://www.warcraftlogs.com/reports/9qhta2r4T3nFpvPx#fight=20&type=auras&source=6

**Comment by Gebuz** [comment] 2018-01-22 11:00
Looks like the issue is that he managed to prepot after the encounter started (iirc this is gonna happen a lot on Aggramar as he is slow to put the rest of the raid in combat), so solution is likely to just check if multiple pots were used during the encounter and if one of them were during the first few seconds assume it was a prepot. It wouldn't be ideal for bosses like Argus where you usually end up using 3 pots in total as it then wouldn't be able to tell the difference between prepotting too late or prepotting successfully but if we don't check for a 3rd pot anyway that is probably fine.

**Comment by abelito75** [comment] 2019-10-28 10:17
This is done closing.

**Closed by abelito75** 2019-10-28 10:17 UTC
Labels: bug
